apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-web-k8s-deployment
  labels:
    app: back-web-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-web-k8s
  template:
    metadata:
      labels:
        app: back-web-k8s
    spec:
      containers:
      - name: back-web-k8s
        image: gcr.io/electro-recipe-app/back-web
        ports:
        - containerPort: 8080