apiVersion: apps/v1
kind: Deployment
metadata:
  name: decider-ms-k8s-deployment
  labels:
    app: decider-ms-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decider-ms-k8s
  template:
    metadata:
      labels:
        app: decider-ms-k8s
    spec:
      containers:
      - name: decider-ms-k8s
        image: gcr.io/electro-recipe-app/decider-ms
        ports:
          - containerPort: 8081
